version: '3.8'

services:
  boiler_plate_db_dev:
    container_name: boiler_plate_db_dev
    image: postgres:13-alpine
    volumes:
      - postgres_boiler_plate_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    env_file:
      - ./.env.dev
    ports:
      - "5435:5432"

  boiler_plate_web_dev:
    container_name: boiler_plate_web_dev
    image: boiler_plate_web_dev_img
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - boiler_plate_db_dev

    env_file:
      - ./.env.dev

volumes:
  postgres_boiler_plate_data:
